// Copyright (C) 2019 - present Juergen Zimmermann, Hochschule Karlsruhe
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

= Entwicklerhandbuch
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: coderay
:icons: font
:plantuml-server-url: http://www.plantuml.com/plantuml

== Der Server

=== Der Server im Überblick

Der Client soll die Möglichkeit haben sich alle Pokemons & und nach gefangene Pokemons suchen können. Zudem soll es ihm möglich sein Pokemons zu gefangen.

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.puml[]
----


=== Der Anwendungskern

In diesem Diagramm kann kann man den Aufbau unseres Anwendungskerns erkennen. Hierbei sendet der Kunde einen Request und in Service wird dieser verarbeitet und ein Response-Objekt erstellt. Dieses erstellte Repsonse-Objekt wird dann dem Kunden zurückgeliefert.

[plantuml,anwendungsker,svg]
----
include::anwendungsker.puml[]
----
Kommentar: Mit unserem Webtool für die Diagramme ist es leider nicht möglich Funktionen in Dateien zu notieren. Daher sind client, db und index leer. Die Inhalte finden Sie im Code. 

== gRPC

=== Die GRPC-Schnittstelle

Im nachfolgenden Diagramm kann man die grobe Struktur unserer gRPC-Schnittstelle erkennen. Wobei die packages pokemon_pb.d und poke_grpc_pb.d aus pokemon.proto mittels dem Skript build.sh erzeugt wurden.

[plantuml,Pokemon,svg]
----
include::Pokemon.puml[]
----

